# Generated by Django 5.1.3 on 2024-11-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_md_ruta_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='md_usuario',
            name='idChatbot',
        ),
        migrations.DeleteModel(
            name='Md_Chatbot',
        ),
    ]
